language: python
cache: yarn
node_js:
  - '13'
  - '12'
  - '10'
  - '8'
before_install:
  - pip install pipenv
install:
  - pipenv install
  - yarn --frozen-lockfile
  - pushd packages/nvlps-currency && yarn --frozen-lockfile && popd
  - pushd packages/nvlps-l10n && yarn --frozen-lockfile && popd
  - pushd packages/nvlps-test && yarn --frozen-lockfile && popd
script:
  - npm run lint
  - npm run bootstrap
  - npm test
  - npm run size
