/* eslint object-curly-newline: 0, wrap-iife: 0 */
/**
 * nvlps-currency Currency Library for nvlps.io
 *
 *   Copyright (c) 2020 Asymworks, LLC.
 *
 *   The nvlps-currency library may be freely distributed under the terms of
 *   the BSD license.  For all licensing information, details and documentation:
 *   https://nvlps.io/nvlps-currency
 *
 * nvlps-currency contains currency and money handling routines for the
 * nvlps.io budgeting software package.  It includes currency information for
 * most world currencies as well as localized formatting, currency symbols, and
 * currency names.
 */

/* Generated by gen_ccy_l10n.py */
import { registerLocale } from '../locale';

const EN = {
  en_AG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_AI: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_AS: {},

  en_AU: {
    e: 'e',
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BAM: 'Bosnia-Herzegovina Convertible Marka',
      BBD: 'Barbados Dollar',
      BMD: 'Bermuda Dollar',
      BOB: 'Boliviano',
      BYN: 'Belarusian Rouble',
      ILS: 'Israeli Shekel',
      QAR: 'Qatari Riyal',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
      SRD: 'Suriname Dollar',
      UYU: 'Peso Uruguayo',
    },
  },

  en_BB: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      BBD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_BE: {
    d: ',',
    g: '.',
    cp: '#,##0.00 ¤',
    ap: '#,##0.00 ¤',
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_BM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      BMD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_BS: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      BSD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_BW: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      BWP: 'P',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_BZ: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      BZD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_CA: {
    e: 'e',
    cs: {
      CAD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_CC: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_CK: {
    cs: {
      JPY: 'JP¥',
      NZD: '$',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_CX: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_DG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_DM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_FJ: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      FJD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_FK: {
    cs: {
      GBP: 'GB£',
      JPY: 'JP¥',
      USD: 'US$',
      FKP: '£',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_FM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GB: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GD: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      GBP: 'UK Pound',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GI: {
    cs: {
      GBP: 'GB£',
      JPY: 'JP¥',
      USD: 'US$',
      GIP: '£',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      GMD: 'D',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_GU: {},

  en_GY: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      GYD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_IE: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_IM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      GBP: 'UK Pound',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_IO: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_JE: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      GBP: 'UK Pound',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_JM: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      JMD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_KI: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_KN: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_KY: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      KYD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_LC: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_LR: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      LRD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_LS: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      ZAR: 'R',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_MH: {},

  en_MP: {},

  en_MS: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_MW: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      MWK: 'MK',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_NF: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_NG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      NGN: '₦',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_NR: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_NU: {
    cs: {
      JPY: 'JP¥',
      NZD: '$',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_NZ: {
    cs: {
      JPY: 'JP¥',
      NZD: '$',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_PG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      PGK: 'K',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_PH: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      PHP: '₱',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_PN: {
    cs: {
      JPY: 'JP¥',
      NZD: '$',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_PW: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SB: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      SBD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      SGD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SH: {
    cs: {
      GBP: 'GB£',
      JPY: 'JP¥',
      USD: 'US$',
      SHP: '£',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SL: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      SLL: 'Le',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SX: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      ANG: 'NAf.',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_SZ: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      SZL: 'E',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_TC: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_TK: {
    cs: {
      JPY: 'JP¥',
      NZD: '$',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_TT: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      TTD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_TV: {
    cs: {
      AUD: '$',
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_UM: {},

  en_VC: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      XCD: '$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_VG: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_VI: {},

  en_VU: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      VUV: 'VT',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_WS: {
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      WST: 'WS$',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },

  en_ZA: {
    d: ',',
    g: ' ',
    cs: {
      JPY: 'JP¥',
      USD: 'US$',
      ZAR: 'R',
    },
    cn: {
      BYN: 'Belarusian Rouble',
      RUB: 'Russian Rouble',
      SHP: 'St Helena Pound',
    },
  },
};

(function register() {
  Object.keys(EN).forEach((k) => {
    registerLocale(k, EN[k]);
  });
})();
