/* eslint object-curly-newline: 0, wrap-iife: 0 */
/**
 * nvlps-currency Currency Library for nvlps.io
 *
 *   Copyright (c) 2020 Asymworks, LLC.
 *
 *   The nvlps-currency library may be freely distributed under the terms of
 *   the BSD license.  For all licensing information, details and documentation:
 *   https://nvlps.io/nvlps-currency
 *
 * nvlps-currency contains currency and money handling routines for the
 * nvlps.io budgeting software package.  It includes currency information for
 * most world currencies as well as localized formatting, currency symbols, and
 * currency names.
 */

/* Generated by gen_ccy_l10n.py */
import { registerLocale } from '../locale';

const HA = {
  ha: {
    d: '.',
    g: ',',
    p: '+',
    m: '-',
    pc: '%',
    pm: '‰',
    e: 'E',
    x: '×',
    inf: '∞',
    nan: 'NaN',
    np: '#,##0.###',
    cp: '¤ #,##0.00',
    ap: '¤ #,##0.00',
    cs: {
      AUD: 'A$',
      BRL: 'R$',
      CAD: 'CA$',
      CNY: 'CN¥',
      EUR: '€',
      GBP: '£',
      HKD: 'HK$',
      ILS: '₪',
      INR: '₹',
      JPY: 'JP¥',
      KRW: '₩',
      MXN: 'MX$',
      NZD: 'NZ$',
      TWD: 'NT$',
      USD: 'US$',
      VND: '₫',
      XAF: 'FCFA',
      XCD: 'EC$',
      XOF: 'CFA',
      XPF: 'CFPF',
      XXX: '¤',
      NGN: '₦',
    },
    cn: {
      AED: 'Kuɗin Haɗaɗɗiyar Daular Larabawa',
      AOA: 'Kuɗin Angola',
      AUD: 'Dalar Ostareliya',
      BHD: 'Kuɗin Baharan',
      BIF: 'Kuɗin Burundi',
      BRL: 'Ril Kudin Birazil',
      BWP: 'Kuɗin Baswana',
      CAD: 'Dalar Kanada',
      CDF: 'Kuɗin Kongo',
      CHF: 'Kuɗin Suwizalan',
      CNY: 'Yuwan kasar Sin',
      CVE: 'Kuɗin Tsibiran Kap Barde',
      DJF: 'Kuɗin Jibuti',
      DZD: 'Kuɗin Aljeriya',
      EGP: 'Fam kin Masar',
      ERN: 'Kuɗin Eritireya',
      ETB: 'Kuɗin Habasha',
      EUR: 'Yuro',
      GBP: 'Fam na Ingila',
      GMD: 'Kuɗin Gambiya',
      INR: 'Kuɗin Indiya',
      JPY: 'Yen kasar Japan',
      KES: 'Sulen Kenya',
      KMF: 'Kuɗin Kwamoras',
      LRD: 'Dalar Laberiya',
      LSL: 'Kuɗin Lesoto',
      LYD: 'Kuɗin Libiya',
      MAD: 'Kuɗin Maroko',
      MGA: 'Kuɗin Madagaskar',
      MRU: 'Kuɗin Moritaniya',
      MUR: 'Kuɗin Moritus',
      MWK: 'Kuɗin Malawi',
      NAD: 'Dalar Namibiya',
      NGN: 'Nairar Najeriya',
      RUB: 'Ruble kasar Rasha',
      RWF: 'Kuɗin Ruwanda',
      SAR: 'Riyal',
      SCR: 'Kuɗin Saishal',
      SDG: 'Fam kin Sudan',
      SHP: 'Fam kin San Helena',
      SLL: 'Kuɗin Salewo',
      SOS: 'Sulen Somaliya',
      STN: 'Kuɗin Sawo Tome da Paransip',
      SZL: 'Kuɗin Lilangeni',
      TND: 'Kuɗin Tunisiya',
      TZS: 'Sulen Tanzaniya',
      UGX: 'Sule Yuganda',
      USD: 'Dalar Amirka',
      XAF: 'Kuɗin Sefa na Afirka Ta Tsakiya',
      XOF: 'Kuɗin Sefa na Afirka Ta Yamma',
      XXX: 'Kudin da ba a sani ba',
      ZAR: 'Kuɗin Afirka Ta Kudu',
      ZMW: 'Kuɗin Zambiya',
    },
  },

  ha_NE: {},
};

(function register() {
  Object.keys(HA).forEach((k) => {
    registerLocale(k, HA[k]);
  });
})();
