/* eslint object-curly-newline: 0 */
/**
 * nvlps-currency Currency Library for nvlps.io
 *
 *   Copyright (c) 2020 Asymworks, LLC.
 *
 *   The nvlps-currency library may be freely distributed under the terms of
 *   the BSD license.  For all licensing information, details and documentation:
 *   https://nvlps.io/nvlps-currency
 *
 * nvlps-currency contains currency and money handling routines for the
 * nvlps.io budgeting software package.  It includes currency information for
 * most world currencies as well as localized formatting, currency symbols, and
 * currency names.
 */

/* Generated by gen_ccy_l10n.py */

import { registerLocales } from 'nvlps-currency-core';

const FR = {
  fr: {
    d: ',',
    g: ' ',
    p: '+',
    m: '-',
    pc: '%',
    pm: '‰',
    e: 'E',
    x: '×',
    inf: '∞',
    nan: 'NaN',
    np: '#,##0.###',
    cp: '#,##0.00 ¤',
    ap: '#,##0.00 ¤;(#,##0.00 ¤)',
    cs: {
      AUD: '$AU',
      BRL: 'R$',
      CAD: '$CA',
      CNY: 'CNY',
      EUR: '€',
      GBP: '£GB',
      HKD: 'HKD',
      ILS: '₪',
      INR: '₹',
      JPY: 'JPY',
      KRW: '₩',
      MXN: 'MX$',
      NZD: '$NZ',
      TWD: 'TWD',
      USD: '$US',
      VND: '₫',
      XAF: 'FCFA',
      XCD: 'EC$',
      XOF: 'CFA',
      XPF: 'FCFP',
      XXX: '¤',
      ARS: '$AR',
      BMD: '$BM',
      BND: '$BN',
      BSD: 'BSD',
      BZD: '$BZ',
      CLP: '$CL',
      COP: '$CO',
      FJD: '$FJ',
      FKP: '£FK',
      GIP: '£GI',
      LBP: '£LB',
      NAD: '$NA',
      SBD: '$SB',
      SGD: '$SG',
      SRD: '$SR',
      TTD: '$TT',
      UYU: '$UY',
      WST: '$WS',
    },
    cn: {
      AED: 'dirham des Émirats arabes unis',
      AFN: 'afghani afghan',
      ALL: 'lek albanais',
      AMD: 'dram arménien',
      ANG: 'florin antillais',
      AOA: 'kwanza angolais',
      ARS: 'peso argentin',
      AUD: 'dollar australien',
      AWG: 'florin arubais',
      AZN: 'manat azéri',
      BAM: 'mark convertible bosniaque',
      BBD: 'dollar barbadien',
      BDT: 'taka bangladeshi',
      BGN: 'lev bulgare',
      BHD: 'dinar bahreïni',
      BIF: 'franc burundais',
      BMD: 'dollar bermudien',
      BND: 'dollar brunéien',
      BOB: 'boliviano bolivien',
      BRL: 'réal brésilien',
      BSD: 'dollar bahaméen',
      BTN: 'ngultrum bouthanais',
      BWP: 'pula botswanais',
      BYN: 'rouble biélorusse',
      BZD: 'dollar bélizéen',
      CAD: 'dollar canadien',
      CDF: 'franc congolais',
      CHF: 'franc suisse',
      CLP: 'peso chilien',
      CNY: 'yuan renminbi chinois',
      COP: 'peso colombien',
      CRC: 'colón costaricain',
      CUC: 'peso cubain convertible',
      CUP: 'peso cubain',
      CVE: 'escudo capverdien',
      CZK: 'couronne tchèque',
      DJF: 'franc djiboutien',
      DKK: 'couronne danoise',
      DOP: 'peso dominicain',
      DZD: 'dinar algérien',
      EGP: 'livre égyptienne',
      ERN: 'nafka érythréen',
      ETB: 'birr éthiopien',
      EUR: 'euro',
      FJD: 'dollar fidjien',
      FKP: 'livre des îles Malouines',
      GBP: 'livre sterling',
      GEL: 'lari géorgien',
      GHS: 'cédi ghanéen',
      GIP: 'livre de Gibraltar',
      GMD: 'dalasi gambien',
      GNF: 'franc guinéen',
      GTQ: 'quetzal guatémaltèque',
      GYD: 'dollar du Guyana',
      HKD: 'dollar de Hong Kong',
      HNL: 'lempira hondurien',
      HRK: 'kuna croate',
      HTG: 'gourde haïtienne',
      HUF: 'forint hongrois',
      IDR: 'roupie indonésienne',
      ILS: 'nouveau shekel israélien',
      INR: 'roupie indienne',
      IQD: 'dinar irakien',
      IRR: 'riyal iranien',
      ISK: 'couronne islandaise',
      JMD: 'dollar jamaïcain',
      JOD: 'dinar jordanien',
      JPY: 'yen japonais',
      KES: 'shilling kényan',
      KGS: 'som kirghize',
      KHR: 'riel cambodgien',
      KMF: 'franc comorien',
      KPW: 'won nord-coréen',
      KRW: 'won sud-coréen',
      KWD: 'dinar koweïtien',
      KYD: 'dollar des îles Caïmans',
      KZT: 'tenge kazakh',
      LAK: 'kip loatien',
      LBP: 'livre libanaise',
      LKR: 'roupie srilankaise',
      LRD: 'dollar libérien',
      LSL: 'loti lesothan',
      LYD: 'dinar libyen',
      MAD: 'dirham marocain',
      MDL: 'leu moldave',
      MGA: 'ariary malgache',
      MKD: 'denar macédonien',
      MMK: 'kyat myanmarais',
      MNT: 'tugrik mongol',
      MOP: 'pataca macanaise',
      MRU: 'ouguiya mauritanien',
      MUR: 'roupie mauricienne',
      MVR: 'rufiyaa maldivien',
      MWK: 'kwacha malawite',
      MXN: 'peso mexicain',
      MYR: 'ringgit malais',
      MZN: 'metical mozambicain',
      NAD: 'dollar namibien',
      NGN: 'naira nigérian',
      NIO: 'córdoba oro nicaraguayen',
      NOK: 'couronne norvégienne',
      NPR: 'roupie népalaise',
      NZD: 'dollar néo-zélandais',
      OMR: 'riyal omanais',
      PAB: 'balboa panaméen',
      PEN: 'sol péruvien',
      PGK: 'kina papouan-néo-guinéen',
      PHP: 'peso philippin',
      PKR: 'roupie pakistanaise',
      PLN: 'zloty polonais',
      PYG: 'guaraní paraguayen',
      QAR: 'riyal qatari',
      RON: 'leu roumain',
      RSD: 'dinar serbe',
      RUB: 'rouble russe',
      RWF: 'franc rwandais',
      SAR: 'riyal saoudien',
      SBD: 'dollar des îles Salomon',
      SCR: 'roupie des Seychelles',
      SDG: 'livre soudanaise',
      SEK: 'couronne suédoise',
      SGD: 'dollar de Singapour',
      SHP: 'livre de Sainte-Hélène',
      SLL: 'leone sierra-léonais',
      SOS: 'shilling somalien',
      SRD: 'dollar surinamais',
      STN: 'dobra santoméen',
      SVC: 'colón salvadorien',
      SYP: 'livre syrienne',
      SZL: 'lilangeni swazi',
      THB: 'baht thaïlandais',
      TJS: 'somoni tadjik',
      TMT: 'nouveau manat turkmène',
      TND: 'dinar tunisien',
      TOP: 'pa’anga tongan',
      TRY: 'livre turque',
      TTD: 'dollar trinidadien',
      TWD: 'nouveau dollar taïwanais',
      TZS: 'shilling tanzanien',
      UAH: 'hryvnia ukrainienne',
      UGX: 'shilling ougandais',
      USD: 'dollar des États-Unis',
      UYU: 'peso uruguayen',
      UZS: 'sum ouzbek',
      VND: 'dông vietnamien',
      VUV: 'vatu vanuatuan',
      WST: 'tala samoan',
      XAF: 'franc CFA (BEAC)',
      XCD: 'dollar des Caraïbes orientales',
      XDR: 'droit de tirage spécial',
      XOF: 'franc CFA (BCEAO)',
      XPF: 'franc CFP',
      XXX: 'devise inconnue ou non valide',
      YER: 'riyal yéménite',
      ZAR: 'rand sud-africain',
      ZMW: 'kwacha zambien',
    },
    c: 'EUR',
  },

  fr_BF: {
    c: 'XOF',
  },

  fr_BJ: {
    c: 'XOF',
  },

  fr_BL: {},

  fr_CF: {
    c: 'XAF',
  },

  fr_CG: {
    c: 'XAF',
  },

  fr_CI: {
    c: 'XOF',
  },

  fr_CM: {
    c: 'XAF',
  },

  fr_FR: {},

  fr_GA: {
    c: 'XAF',
  },

  fr_GF: {},

  fr_GN: {
    cs: {
      GNF: 'FG',
    },
    c: 'GNF',
  },

  fr_GP: {},

  fr_HT: {
    cs: {
      HTG: 'G',
    },
    c: 'HTG',
  },

  fr_LU: {
    g: '.',
  },

  fr_MC: {},

  fr_MF: {},

  fr_MQ: {},

  fr_NC: {
    c: 'XPF',
  },

  fr_PF: {
    c: 'XPF',
  },

  fr_PM: {},

  fr_RE: {},

  fr_SC: {
    cs: {
      SCR: 'SR',
    },
    c: 'SCR',
  },

  fr_TD: {
    c: 'XAF',
  },

  fr_TG: {
    c: 'XOF',
  },

  fr_WF: {
    c: 'XPF',
  },

  fr_YT: {},
};

registerLocales(FR);

export default FR;
