/* eslint object-curly-newline: 0 */
/**
 * nvlps-currency Currency Library for nvlps.io
 *
 *   Copyright (c) 2020 Asymworks, LLC.
 *
 *   The nvlps-currency library may be freely distributed under the terms of
 *   the BSD license.  For all licensing information, details and documentation:
 *   https://nvlps.io/nvlps-currency
 *
 * nvlps-currency contains currency and money handling routines for the
 * nvlps.io budgeting software package.  It includes currency information for
 * most world currencies as well as localized formatting, currency symbols, and
 * currency names.
 */

/* Generated by gen_ccy_l10n.py */

// Find nvlps if it was loaded into the root namespace
if (
  typeof window.nvlps === 'undefined' ||
  typeof window.nvlps.registerLocales !== 'function'
) {
  throw 'The nvlps-currency library must be imported into the "nvlps" namespace prior to including this localization module';
}

// Locale Data for RN
var RN = {
  rn: {
    d: ',',
    g: '.',
    p: '+',
    m: '-',
    pc: '%',
    pm: '‰',
    e: 'E',
    x: '×',
    inf: '∞',
    nan: 'NaN',
    np: '#,##0.###',
    cp: '#,##0.00¤',
    ap: '#,##0.00¤',
    cs: {
      AUD: 'A$',
      BRL: 'R$',
      CAD: 'CA$',
      CNY: 'CN¥',
      EUR: '€',
      GBP: '£',
      HKD: 'HK$',
      ILS: '₪',
      INR: '₹',
      JPY: 'JP¥',
      KRW: '₩',
      MXN: 'MX$',
      NZD: 'NZ$',
      TWD: 'NT$',
      USD: 'US$',
      VND: '₫',
      XAF: 'FCFA',
      XCD: 'EC$',
      XOF: 'CFA',
      XPF: 'CFPF',
      XXX: '¤',
      BIF: 'FBu',
    },
    cn: {
      AED: 'Idiramu ryo muri Leta Zunze Ubumwe z’Abarabu',
      AOA: 'Ikwanza ryo muri Angola',
      AUD: 'Idolari ryo muri Ositaraliya',
      BHD: 'Idinari ry’iribahireyini',
      BIF: 'Ifaranga ry’Uburundi',
      BWP: 'Ipula ryo muri Botswana',
      CAD: 'Idolari rya Kanada',
      CDF: 'Ifaranga rya Kongo',
      CHF: 'Ifaranga ry’Ubusuwisi',
      CNY: 'Iyuwani ryo mu Bushinwa',
      CVE: 'Irikaboveridiyano ryo muri Esikudo',
      DJF: 'Ifaranga ryo muri Jibuti',
      DZD: 'Idinari ryo muri Alijeriya',
      EGP: 'Ipawundi rya Misiri',
      ERN: 'Irinakufa ryo muri Eritereya',
      ETB: 'Ibiri ryo muri Etiyopiya',
      EUR: 'Iyero',
      GBP: 'Ipawundi ryo mu Bwongereza',
      GMD: 'Idalasi ryo muri Gambiya',
      INR: 'Irupiya ryo mu Buhindi',
      JPY: 'Iyeni ry’Ubuyapani',
      KES: 'Ishilingi rya Kenya',
      KMF: 'Ifaranga rya Komore',
      LRD: 'Idolari rya Liberiya',
      LSL: 'Iloti ryo muro Lesoto',
      LYD: 'Idinari rya Libiya',
      MAD: 'Idiramu ryo muri Maroke',
      MGA: 'Iriyari ryo muri Madagasikari',
      MRU: 'Ugwiya ryo muri Moritaniya',
      MUR: 'Irupiya ryo mu birwa bya Morise',
      MWK: 'Ikwaca ryo muri Malawi',
      NAD: 'Idolari rya Namibiya',
      NGN: 'Inayira ryo muri Nijeriya',
      RWF: 'Ifaranga ry’u Rwanda',
      SAR: 'Iriyari ryo muri Arabiya Sawudite',
      SCR: 'Irupiya ryo mu birwa bya Sayisheli',
      SDG: 'Ipawundi rya Sudani',
      SHP: 'Ipawundi rya Sente Helena',
      SLL: 'Ilewone',
      SOS: 'Ishilingi ryo muri Somaliya',
      STN: 'Idobura ryo muri Sawotome na Perensipe',
      SZL: 'Ililangeni',
      TND: 'Idinari ryo muri Tuniziya',
      TZS: 'Ishilingi rya Tanzaniya',
      UGX: 'Ishilingi ry’Ubugande',
      USD: 'Idolari ry’abanyamerika',
      ZAR: 'Irandi ryo muri Afurika y’Epfo',
      ZMW: 'Ikwaca ryo muri Zambiya',
    },
  },

  rn_BI: {},
};

// Register the Locale Data with nvlps-currency
window.nvlps.registerLocales(RN);
