/**
 * nvlps-currency Currency Library for nvlps.io
 *
 *   Copyright (c) 2020 Asymworks, LLC.
 *
 *   The nvlps-currency library may be freely distributed under the terms of
 *   the BSD license.  For all licensing information, details and documentation:
 *   https://nvlps.io/nvlps-currency
 *
 * nvlps-currency contains currency and money handling routines for the
 * nvlps.io budgeting software package.  It includes currency information for
 * most world currencies as well as localized formatting, currency symbols, and
 * currency names.
 */

/* Generated by gen_ccy_l10n.py */

import AF from './locales/af';
import AK from './locales/ak';
import AM from './locales/am';
import AR from './locales/ar';
import AZ from './locales/az';
import BE from './locales/be';
import BEM from './locales/bem';
import BG from './locales/bg';
import BM from './locales/bm';
import BN from './locales/bn';
import BS from './locales/bs';
import CA from './locales/ca';
import CS from './locales/cs';
import DA from './locales/da';
import DE from './locales/de';
import DZ from './locales/dz';
import EL from './locales/el';
import EN from './locales/en';
import ES from './locales/es';
import ET from './locales/et';
import FA from './locales/fa';
import FI from './locales/fi';
import FO from './locales/fo';
import FR from './locales/fr';
import HA from './locales/ha';
import HE from './locales/he';
import HI from './locales/hi';
import HR from './locales/hr';
import HU from './locales/hu';
import HY from './locales/hy';
import ID from './locales/id';
import IS from './locales/is';
import IT from './locales/it';
import JA from './locales/ja';
import KA from './locales/ka';
import KEA from './locales/kea';
import KL from './locales/kl';
import KM from './locales/km';
import KO from './locales/ko';
import KY from './locales/ky';
import LO from './locales/lo';
import LT from './locales/lt';
import LV from './locales/lv';
import MFE from './locales/mfe';
import MG from './locales/mg';
import MK from './locales/mk';
import MN from './locales/mn';
import MS from './locales/ms';
import MT from './locales/mt';
import MY from './locales/my';
import NB from './locales/nb';
import NE from './locales/ne';
import NL from './locales/nl';
import PL from './locales/pl';
import PT from './locales/pt';
import RN from './locales/rn';
import RO from './locales/ro';
import RU from './locales/ru';
import RW from './locales/rw';
import SI from './locales/si';
import SK from './locales/sk';
import SL from './locales/sl';
import SN from './locales/sn';
import SO from './locales/so';
import SQ from './locales/sq';
import SR from './locales/sr';
import SV from './locales/sv';
import SW from './locales/sw';
import TG from './locales/tg';
import TH from './locales/th';
import TI from './locales/ti';
import TK from './locales/tk';
import TO from './locales/to';
import TR from './locales/tr';
import UK from './locales/uk';
import UR from './locales/ur';
import UZ from './locales/uz';
import VI from './locales/vi';
import WO from './locales/wo';
import YUE from './locales/yue';
import ZH from './locales/zh';

export {
  AF,
  AK,
  AM,
  AR,
  AZ,
  BE,
  BEM,
  BG,
  BM,
  BN,
  BS,
  CA,
  CS,
  DA,
  DE,
  DZ,
  EL,
  EN,
  ES,
  ET,
  FA,
  FI,
  FO,
  FR,
  HA,
  HE,
  HI,
  HR,
  HU,
  HY,
  ID,
  IS,
  IT,
  JA,
  KA,
  KEA,
  KL,
  KM,
  KO,
  KY,
  LO,
  LT,
  LV,
  MFE,
  MG,
  MK,
  MN,
  MS,
  MT,
  MY,
  NB,
  NE,
  NL,
  PL,
  PT,
  RN,
  RO,
  RU,
  RW,
  SI,
  SK,
  SL,
  SN,
  SO,
  SQ,
  SR,
  SV,
  SW,
  TG,
  TH,
  TI,
  TK,
  TO,
  TR,
  UK,
  UR,
  UZ,
  VI,
  WO,
  YUE,
  ZH,
};
